'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=4.0.30319.1.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="SyncShellTargetedOffersBinding", [Namespace]:="http://webservices.sig.aholdusa.com/loyalty/fuel/LoyaltyManager"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(AmountCommonData))>  _
Public Interface ISyncShellTargetedOffersBinding
    
    '''<remarks/>
    <System.Web.Services.WebMethodAttribute(),  _
     System.Web.Services.Protocols.SoapDocumentMethodAttribute("SyncShellTargetedOffersBinding_GetTargetedOffers", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
    Function GetTargetedOffers(<System.Xml.Serialization.XmlElementAttribute("GetTargetedOffers", [Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")> ByVal GetTargetedOffers1 As CustomerType) As <System.Xml.Serialization.XmlElementAttribute("ShowTargetedOffers", [Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")> CustomerType
    
    '''<remarks/>
    <System.Web.Services.WebMethodAttribute(),  _
     System.Web.Services.Protocols.SoapDocumentMethodAttribute("SyncShellTargetedOffersBinding_ProcessTargetedOffers", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
    Function ProcessTargetedOffers(<System.Xml.Serialization.XmlElementAttribute("ProcessTargetedOffers", [Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")> ByVal ProcessTargetedOffers1 As CustomerType) As <System.Xml.Serialization.XmlElementAttribute("AcknowledgeTargetedOffers", [Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")> CustomerType
    
    '''<remarks/>
    <System.Web.Services.WebMethodAttribute(),  _
     System.Web.Services.Protocols.SoapDocumentMethodAttribute("SyncShellTargetedOffersBinding_GetNetworkManagement", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
    Function GetNetworkManagement(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")> ByVal NWMRequest As NWMType) As <System.Xml.Serialization.XmlElementAttribute("NWMResponse", [Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")> NWMType
End Interface

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class CustomerType
    
    Private actionField As CustomerActionType
    
    Private responseCodeField As ResponseCodeType
    
    Private responseCodeFieldSpecified As Boolean
    
    Private responseDescriptionField As String
    
    Private messageTimestampField As Date
    
    Private pOSTimestampField As Date
    
    Private loyaltyAccountField As LoyaltyAccountType
    
    Private securityAgreementField As SecurityArrangementType
    
    Private shoppingBasketField As BasketType
    
    Private promotionField As PromotionIDType
    
    Private totalDiscountAmountField As MonetaryAmountType
    
    Private partnerSpecificDataField() As PartnerSpecificType
    
    '''<remarks/>
    Public Property Action() As CustomerActionType
        Get
            Return Me.actionField
        End Get
        Set
            Me.actionField = value
        End Set
    End Property

    '''<remarks/>
    Public Property ResponseCode() As ResponseCodeType
        Get
            Return Me.responseCodeField
        End Get
        Set
            Me.responseCodeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ResponseCodeSpecified() As Boolean
        Get
            Return Me.responseCodeFieldSpecified
        End Get
        Set
            Me.responseCodeFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ResponseDescription() As String
        Get
            Return Me.responseDescriptionField
        End Get
        Set
            Me.responseDescriptionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property MessageTimestamp() As Date
        Get
            Return Me.messageTimestampField
        End Get
        Set
            Me.messageTimestampField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property POSTimestamp() As Date
        Get
            Return Me.pOSTimestampField
        End Get
        Set
            Me.pOSTimestampField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property LoyaltyAccount() As LoyaltyAccountType
        Get
            Return Me.loyaltyAccountField
        End Get
        Set
            Me.loyaltyAccountField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property SecurityAgreement() As SecurityArrangementType
        Get
            Return Me.securityAgreementField
        End Get
        Set
            Me.securityAgreementField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ShoppingBasket() As BasketType
        Get
            Return Me.shoppingBasketField
        End Get
        Set
            Me.shoppingBasketField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Promotion() As PromotionIDType
        Get
            Return Me.promotionField
        End Get
        Set
            Me.promotionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TotalDiscountAmount() As MonetaryAmountType
        Get
            Return Me.totalDiscountAmountField
        End Get
        Set
            Me.totalDiscountAmountField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("PartnerSpecificData")>  _
    Public Property PartnerSpecificData() As PartnerSpecificType()
        Get
            Return Me.partnerSpecificDataField
        End Get
        Set
            Me.partnerSpecificDataField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Public Enum CustomerActionType
    
    '''<remarks/>
    CheckForTargetedOffer
    
    '''<remarks/>
    PointsRedemption
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Public Enum ResponseCodeType
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("KA:ValidAccountWithDiscount")>  _
    KAValidAccountWithDiscount
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("KB:ValidAccountWithoutDiscount")>  _
    KBValidAccountWithoutDiscount
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("KC:UnknownAccount")>  _
    KCUnknownAccount
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("KD:UnknownSite")>  _
    KDUnknownSite
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("KE:InvalidArrangementID")>  _
    KEInvalidArrangementID
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("KF:ExpiredArrangementID")>  _
    KFExpiredArrangementID
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("KG:InvalidMessageFormat")>  _
    KGInvalidMessageFormat
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("KH:InvalidMessageData")>  _
    KHInvalidMessageData
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class LoyaltyAccountType
    
    Private updateTypeField As CustomerUpdateType
    
    Private loyaltyAccountIDField As String
    
    Private entryMethodField As EntryMethodTypeCode
    
    Public Sub New()
        MyBase.New
        Me.updateTypeField = CustomerUpdateType.Existing
        Me.entryMethodField = EntryMethodTypeCode.Scanned
    End Sub
    
    '''<remarks/>
    Public Property UpdateType() As CustomerUpdateType
        Get
            Return Me.updateTypeField
        End Get
        Set
            Me.updateTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property LoyaltyAccountID() As String
        Get
            Return Me.loyaltyAccountIDField
        End Get
        Set
            Me.loyaltyAccountIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property EntryMethod() As EntryMethodTypeCode
        Get
            Return Me.entryMethodField
        End Get
        Set
            Me.entryMethodField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Public Enum CustomerUpdateType
    
    '''<remarks/>
    Existing
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Public Enum EntryMethodTypeCode
    
    '''<remarks/>
    Scanned
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class NWMType
    
    Private networkActionField As String
    
    Private transDateTimeField As String
    
    Private traceNumField As String
    
    Private settlementDateField As String
    
    Private nWMCodeField As String
    
    '''<remarks/>
    Public Property NetworkAction() As String
        Get
            Return Me.networkActionField
        End Get
        Set
            Me.networkActionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TransDateTime() As String
        Get
            Return Me.transDateTimeField
        End Get
        Set
            Me.transDateTimeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TraceNum() As String
        Get
            Return Me.traceNumField
        End Get
        Set
            Me.traceNumField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property SettlementDate() As String
        Get
            Return Me.settlementDateField
        End Get
        Set
            Me.settlementDateField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property NWMCode() As String
        Get
            Return Me.nWMCodeField
        End Get
        Set
            Me.nWMCodeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class PartnerSpecificType
    
    Private descriptionField As String
    
    Private valueField As String
    
    '''<remarks/>
    Public Property Description() As String
        Get
            Return Me.descriptionField
        End Get
        Set
            Me.descriptionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.Xml.Serialization.XmlIncludeAttribute(GetType(MonetaryAmountCommonData)),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class AmountCommonData
    
    Private valueField As Decimal
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As Decimal
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class MonetaryAmountCommonData
    Inherits AmountCommonData
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class MonetaryAmountType
    
    Private amountField As MonetaryAmountTypeAmount
    
    Private currencyField As CurrencyCode
    
    Public Sub New()
        MyBase.New
        Me.currencyField = CurrencyCode.USD
    End Sub
    
    '''<remarks/>
    Public Property Amount() As MonetaryAmountTypeAmount
        Get
            Return Me.amountField
        End Get
        Set
            Me.amountField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Currency() As CurrencyCode
        Get
            Return Me.currencyField
        End Get
        Set
            Me.currencyField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class MonetaryAmountTypeAmount
    Inherits MonetaryAmountCommonData
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Public Enum CurrencyCode
    
    '''<remarks/>
    USD
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class PromotionIDType
    
    Private couponIDField As String
    
    Private discountAmountField As MonetaryAmountType
    
    Private itemField As ItemType
    
    Private quantityLimitField As QuantityType
    
    '''<remarks/>
    Public Property CouponID() As String
        Get
            Return Me.couponIDField
        End Get
        Set
            Me.couponIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property DiscountAmount() As MonetaryAmountType
        Get
            Return Me.discountAmountField
        End Get
        Set
            Me.discountAmountField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Item() As ItemType
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property QuantityLimit() As QuantityType
        Get
            Return Me.quantityLimitField
        End Get
        Set
            Me.quantityLimitField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class ItemType
    
    Private itemIDField As String
    
    Private typeField As ItemIDTypeCode
    
    Private qualifierField As String
    
    Private quantityField As QuantityType
    
    Public Sub New()
        MyBase.New
        Me.typeField = ItemIDTypeCode.UPC
        Me.qualifierField = "NACS"
    End Sub
    
    '''<remarks/>
    Public Property ItemID() As String
        Get
            Return Me.itemIDField
        End Get
        Set
            Me.itemIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Type() As ItemIDTypeCode
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Qualifier() As String
        Get
            Return Me.qualifierField
        End Get
        Set
            Me.qualifierField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Quantity() As QuantityType
        Get
            Return Me.quantityField
        End Get
        Set
            Me.quantityField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Public Enum ItemIDTypeCode
    
    '''<remarks/>
    UPC
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class QuantityType
    
    Private unitsField As Decimal
    
    Private unitOfMeasureCodeField As UnitOfMeasureCodeCommonData
    
    Public Sub New()
        MyBase.New
        Me.unitOfMeasureCodeField = UnitOfMeasureCodeCommonData.GLL
    End Sub
    
    '''<remarks/>
    Public Property Units() As Decimal
        Get
            Return Me.unitsField
        End Get
        Set
            Me.unitsField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property UnitOfMeasureCode() As UnitOfMeasureCodeCommonData
        Get
            Return Me.unitOfMeasureCodeField
        End Get
        Set
            Me.unitOfMeasureCodeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Public Enum UnitOfMeasureCodeCommonData
    
    '''<remarks/>
    GLL
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class SiteIDCommonData
    
    Private siteIDField As String
    
    Private nameField As String
    
    Private typeCodeField As SiteTypeCode
    
    Public Sub New()
        MyBase.New
        Me.typeCodeField = SiteTypeCode.RetailStore
    End Sub
    
    '''<remarks/>
    Public Property SiteID() As String
        Get
            Return Me.siteIDField
        End Get
        Set
            Me.siteIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TypeCode() As SiteTypeCode
        Get
            Return Me.typeCodeField
        End Get
        Set
            Me.typeCodeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Public Enum SiteTypeCode
    
    '''<remarks/>
    RetailStore
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class OldTransactionLinkCommonData
    
    Private reasonCodeField As OldTransactionLinkCommonDataReasonCode
    
    Private siteField As SiteIDCommonData
    
    Private workstationIDField As String
    
    Private sequenceNumberField As ULong
    
    Public Sub New()
        MyBase.New
        Me.reasonCodeField = OldTransactionLinkCommonDataReasonCode.RetrospectiveLoyalty
    End Sub
    
    '''<remarks/>
    Public Property ReasonCode() As OldTransactionLinkCommonDataReasonCode
        Get
            Return Me.reasonCodeField
        End Get
        Set
            Me.reasonCodeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Site() As SiteIDCommonData
        Get
            Return Me.siteField
        End Get
        Set
            Me.siteField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property WorkstationID() As String
        Get
            Return Me.workstationIDField
        End Get
        Set
            Me.workstationIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property SequenceNumber() As ULong
        Get
            Return Me.sequenceNumberField
        End Get
        Set
            Me.sequenceNumberField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Public Enum OldTransactionLinkCommonDataReasonCode
    
    '''<remarks/>
    RetrospectiveLoyalty
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class BasketType
    
    Private transactionLinkField As OldTransactionLinkCommonData
    
    Private itemField() As ItemType
    
    '''<remarks/>
    Public Property TransactionLink() As OldTransactionLinkCommonData
        Get
            Return Me.transactionLinkField
        End Get
        Set
            Me.transactionLinkField = value
        End Set
    End Property
    
    '''<remarks/>
  <System.Xml.Serialization.XmlElementAttribute("Item")> _
  Public Property Item() As ItemType()
    Get
      Return Me.itemField
    End Get
    Set(ByVal value As ItemType())
      Me.itemField = Value
    End Set
  End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schema.aholdusa.com/loyalty/fuel/LoyaltyManager")>  _
Partial Public Class SecurityArrangementType
    
    Private arrangementIDField As String
    
    Private expirationDateField As Date
    
    '''<remarks/>
    Public Property ArrangementID() As String
        Get
            Return Me.arrangementIDField
        End Get
        Set
            Me.arrangementIDField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
    Public Property ExpirationDate() As Date
        Get
            Return Me.expirationDateField
        End Get
        Set
            Me.expirationDateField = value
        End Set
    End Property
End Class
